name: Windows tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Py${{ matrix.PYTHON_VERSION }}, ${{ matrix.INSTALL_TYPE }}
    runs-on: windows-latest
    env:
      CI: 'true'
      CODECOV_TOKEN: "273c981b-7851-4895-a4bb-07377c67791e"
      OS: 'win'
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      USE_CONDA: ${{ matrix.INSTALL_TYPE == 'conda' }}
      USE_GDB: 'false'
    strategy:
      fail-fast: false
      matrix:
        INSTALL_TYPE: ['conda']
        PYTHON_VERSION: ['3.9', '3.11', '3.13']
    timeout-minutes: 120
    steps:
      - name: checkout branch
        uses: actions/checkout@v4
      - name : Setup miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
            python-version: ${{ matrix.PYTHON_VERSION }}
            channels: conda-forge,defaults
            channel-priority: true
            activate-environment: test
            miniforge-version: latest
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Create test environment
        shell: bash -l {0}
        run: bash -l .github/scripts/install.sh
      - name: Show test environment
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Build static resources
        shell: bash -l {0}
        run: python setup.py build_static
      - name: Run tests
        shell: bash -l {0}
        run: python runtests.py || python runtests.py || python runtests.py || python runtests.py || python runtests.py
      - name: Coverage
        shell: bash -l {0}
        run: codecov
